-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 06:28:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `idprofile` INT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(100) NULL,
  `alamat_email` VARCHAR(100) NULL,
  `photo` VARCHAR(100) NULL,
  PRIMARY KEY (`idprofile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertanyaan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pertanyaan` (
  `idpertanyaan` VARCHAR(45) NOT NULL,
  `judul` VARCHAR(100) NULL,
  `isi` LONGTEXT NULL,
  `tanggal_dibuat` DATE NULL,
  `tanggal_diperbarui` DATE NULL,
  PRIMARY KEY (`idpertanyaan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jawaban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jawaban` (
  `idjawaban` VARCHAR(45) NOT NULL,
  `isi` LONGTEXT NULL,
  `tanggal_dibuat` DATE NULL,
  `tanggal_diperbarui` DATE NULL,
  `idpertanyaan` INT NULL,
  PRIMARY KEY (`idjawaban`),
  INDEX `idpertanyaan_idx` (`idpertanyaan` ASC) VISIBLE,
  CONSTRAINT `idpertanyaan`
    FOREIGN KEY (`idpertanyaan`)
    REFERENCES `mydb`.`pertanyaan` (`idpertanyaan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`komentar` (
  `idkomentar` INT NOT NULL AUTO_INCREMENT,
  `isi` LONGTEXT NULL,
  `tanggal_dibuat` DATE NULL,
  `pemberi_komentar_id` INT NOT NULL,
  `id_tujuan` VARCHAR(45) NULL,
  PRIMARY KEY (`idkomentar`),
  INDEX `idprofile_idx` (`pemberi_komentar_id` ASC) VISIBLE,
  INDEX `idpertanyaan_idx` (`id_tujuan` ASC) VISIBLE,
  CONSTRAINT `idprofile`
    FOREIGN KEY (`pemberi_komentar_id`)
    REFERENCES `mydb`.`profile` (`idprofile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpertanyaan`
    FOREIGN KEY (`id_tujuan`)
    REFERENCES `mydb`.`pertanyaan` (`idpertanyaan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idjawaban`
    FOREIGN KEY (`id_tujuan`)
    REFERENCES `mydb`.`jawaban` (`idjawaban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likedislike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likedislike` (
  `idlikedislike` INT NOT NULL AUTO_INCREMENT,
  `idprofile` INT NULL,
  `id_tujuan` VARCHAR(45) NULL,
  `status` ENUM('like', 'dislike') NULL,
  PRIMARY KEY (`idlikedislike`),
  INDEX `idprofile_idx` (`idprofile` ASC) VISIBLE,
  INDEX `idpertanyaan_idx` (`id_tujuan` ASC) VISIBLE,
  CONSTRAINT `idprofile`
    FOREIGN KEY (`idprofile`)
    REFERENCES `mydb`.`profile` (`idprofile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpertanyaan`
    FOREIGN KEY (`id_tujuan`)
    REFERENCES `mydb`.`pertanyaan` (`idpertanyaan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idjawaban`
    FOREIGN KEY (`id_tujuan`)
    REFERENCES `mydb`.`jawaban` (`idjawaban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`jumlahVote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jumlahVote` (`SUM(status = 'like') - SUM(status = 'dislike')` INT);

-- -----------------------------------------------------
-- View `mydb`.`jumlahVote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jumlahVote`;
USE `mydb`;
CREATE  OR REPLACE VIEW `jumlahVote` AS
    SELECT 
        SUM(status = 'like') - SUM(status = 'dislike') 
    FROM
        likedislike group by id_tujuan;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
